alter table "public"."motion_video_segmentation" drop constraint "motion_video_segmentation_created_for_fkey";

alter table "public"."motion_video_segmentation" drop constraint "motion_video_segmentation_video_id_fkey";

alter table "public"."user_learning_model" drop constraint "user_learning_model_segmentation_id_fkey";

alter table "public"."user_learning_model" drop constraint "user_learning_model_user_id_fkey";

alter table "public"."user_learning_model" drop constraint "user_learning_model_user_id_video_id_segmentation_id_key";

alter table "public"."user_learning_model" drop constraint "user_learning_model_video_id_fkey";

alter table "public"."motion_video_segmentation" drop constraint "motion_video_segmentation_pkey";

alter table "public"."user_learning_model" drop constraint "user_learning_model_pkey";

drop index if exists "public"."motion_video_segmentation_pkey";

drop index if exists "public"."user_learning_model_pkey";

drop index if exists "public"."user_learning_model_user_id_video_id_segmentation_id_key";

create table "public"."ai_postperformance_action" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "action_name" text not null,
    "data" jsonb not null,
    "practice_attempt" bigint not null
);


alter table "public"."ai_postperformance_action" enable row level security;

alter table "public"."user_performance_attempt" drop column "video_recording_url";

alter table "public"."user_performance_attempt" add column "video_recording_storagepath" text;

alter table "public"."user_performance_attempt" alter column "id" set generated by default;

CREATE UNIQUE INDEX ai_postperformance_action_pkey ON public.ai_postperformance_action USING btree (id);

CREATE UNIQUE INDEX ai_postperformance_action_practice_attempt_key ON public.ai_postperformance_action USING btree (practice_attempt);

CREATE UNIQUE INDEX motion_segmentation_pkey ON public.motion_video_segmentation USING btree (id);

CREATE UNIQUE INDEX motion_userstate_pkey ON public.user_learning_model USING btree (id);

CREATE UNIQUE INDEX motion_userstate_user_id_video_id_segmentation_id_key ON public.user_learning_model USING btree (user_id, video_id, segmentation_id);

alter table "public"."ai_postperformance_action" add constraint "ai_postperformance_action_pkey" PRIMARY KEY using index "ai_postperformance_action_pkey";

alter table "public"."motion_video_segmentation" add constraint "motion_segmentation_pkey" PRIMARY KEY using index "motion_segmentation_pkey";

alter table "public"."user_learning_model" add constraint "motion_userstate_pkey" PRIMARY KEY using index "motion_userstate_pkey";

alter table "public"."ai_postperformance_action" add constraint "ai_postperformance_action_practice_attempt_fkey" FOREIGN KEY (practice_attempt) REFERENCES user_performance_attempt(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ai_postperformance_action" validate constraint "ai_postperformance_action_practice_attempt_fkey";

alter table "public"."ai_postperformance_action" add constraint "ai_postperformance_action_practice_attempt_key" UNIQUE using index "ai_postperformance_action_practice_attempt_key";

alter table "public"."motion_video_segmentation" add constraint "motion_segmentation_createdFor_fkey" FOREIGN KEY (created_for) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."motion_video_segmentation" validate constraint "motion_segmentation_createdFor_fkey";

alter table "public"."motion_video_segmentation" add constraint "motion_segmentation_videoId_fkey" FOREIGN KEY (video_id) REFERENCES motion_video(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."motion_video_segmentation" validate constraint "motion_segmentation_videoId_fkey";

alter table "public"."user_learning_model" add constraint "motion_userstate_segmentation_id_fkey" FOREIGN KEY (segmentation_id) REFERENCES motion_video_segmentation(id) not valid;

alter table "public"."user_learning_model" validate constraint "motion_userstate_segmentation_id_fkey";

alter table "public"."user_learning_model" add constraint "motion_userstate_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."user_learning_model" validate constraint "motion_userstate_user_id_fkey";

alter table "public"."user_learning_model" add constraint "motion_userstate_user_id_video_id_segmentation_id_key" UNIQUE using index "motion_userstate_user_id_video_id_segmentation_id_key";

alter table "public"."user_learning_model" add constraint "motion_userstate_video_id_fkey" FOREIGN KEY (video_id) REFERENCES motion_video(id) not valid;

alter table "public"."user_learning_model" validate constraint "motion_userstate_video_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.prevent_user_supplied_id_user_learning_model()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- If client supplied an id (non-null), override it. If NULL (no value supplied),
    -- the DEFAULT expression has already populated NEW.id before this trigger fires.
    IF TG_OP = 'INSERT' AND NEW.id IS NOT NULL THEN
        -- Always ensure the id is server-generated (idempotent if it already was)
        NEW.id = gen_random_uuid();
    END IF;
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."ai_postperformance_action" to "anon";

grant insert on table "public"."ai_postperformance_action" to "anon";

grant references on table "public"."ai_postperformance_action" to "anon";

grant select on table "public"."ai_postperformance_action" to "anon";

grant trigger on table "public"."ai_postperformance_action" to "anon";

grant truncate on table "public"."ai_postperformance_action" to "anon";

grant update on table "public"."ai_postperformance_action" to "anon";

grant delete on table "public"."ai_postperformance_action" to "authenticated";

grant insert on table "public"."ai_postperformance_action" to "authenticated";

grant references on table "public"."ai_postperformance_action" to "authenticated";

grant select on table "public"."ai_postperformance_action" to "authenticated";

grant trigger on table "public"."ai_postperformance_action" to "authenticated";

grant truncate on table "public"."ai_postperformance_action" to "authenticated";

grant update on table "public"."ai_postperformance_action" to "authenticated";

grant delete on table "public"."ai_postperformance_action" to "service_role";

grant insert on table "public"."ai_postperformance_action" to "service_role";

grant references on table "public"."ai_postperformance_action" to "service_role";

grant select on table "public"."ai_postperformance_action" to "service_role";

grant trigger on table "public"."ai_postperformance_action" to "service_role";

grant truncate on table "public"."ai_postperformance_action" to "service_role";

grant update on table "public"."ai_postperformance_action" to "service_role";

-- Enforce server-generated identity for ai_postperformance_action.id
alter table "public"."ai_postperformance_action"
    alter column "id" set generated always;

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.enforce_id_ai_postperformance_action()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- If client supplied an id, override with next identity value
        IF NEW.id IS NOT NULL THEN
            NEW.id := nextval(pg_get_serial_sequence('public.ai_postperformance_action','id'));
        END IF;
    ELSIF TG_OP = 'UPDATE' THEN
        -- Prevent id changes on update
        IF NEW.id IS DISTINCT FROM OLD.id THEN
            NEW.id := OLD.id;
        END IF;
    END IF;
    RETURN NEW;
END;
$function$;

-- Recreate triggers idempotently
DROP TRIGGER IF EXISTS enforce_id_ai_postperformance_action_ins ON public.ai_postperformance_action;
CREATE TRIGGER enforce_id_ai_postperformance_action_ins
    BEFORE INSERT ON public.ai_postperformance_action
    FOR EACH ROW
    EXECUTE FUNCTION public.enforce_id_ai_postperformance_action();

DROP TRIGGER IF EXISTS enforce_id_ai_postperformance_action_upd ON public.ai_postperformance_action;
CREATE TRIGGER enforce_id_ai_postperformance_action_upd
    BEFORE UPDATE OF id ON public.ai_postperformance_action
    FOR EACH ROW
    EXECUTE FUNCTION public.enforce_id_ai_postperformance_action();

set check_function_bodies = on;
