create table "public"."user_performance_attempt" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "motion_id" bigint not null,
    "learningmodel_id" uuid not null,
    "evaluation" jsonb not null,
    "self_report" jsonb not null,
    "practice_context" jsonb not null,
    "video_recording_url" text,
    "duration_secs" double precision
);

alter table "public"."user_performance_attempt" enable row level security;

alter table "public"."user_performance_attempt" add constraint "user_performance_attempt_pkey" PRIMARY KEY (id);

alter table "public"."user_performance_attempt" add constraint "user_performance_attempt_learningmodel_id_fkey" FOREIGN KEY (learningmodel_id) REFERENCES user_learning_model(id) ON UPDATE CASCADE ON DELETE CASCADE;

alter table "public"."user_performance_attempt" add constraint "user_performance_attempt_motion_id_fkey" FOREIGN KEY (motion_id) REFERENCES motion_video(id) ON UPDATE CASCADE ON DELETE CASCADE;

alter table "public"."user_performance_attempt" add constraint "user_performance_attempt_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE;

grant delete on table "public"."user_performance_attempt" to "anon";
grant insert on table "public"."user_performance_attempt" to "anon";
grant references on table "public"."user_performance_attempt" to "anon";
grant select on table "public"."user_performance_attempt" to "anon";
grant trigger on table "public"."user_performance_attempt" to "anon";
grant truncate on table "public"."user_performance_attempt" to "anon";
grant update on table "public"."user_performance_attempt" to "anon";
grant delete on table "public"."user_performance_attempt" to "authenticated";
grant insert on table "public"."user_performance_attempt" to "authenticated";
grant references on table "public"."user_performance_attempt" to "authenticated";
grant select on table "public"."user_performance_attempt" to "authenticated";
grant trigger on table "public"."user_performance_attempt" to "authenticated";
grant truncate on table "public"."user_performance_attempt" to "authenticated";
grant update on table "public"."user_performance_attempt" to "authenticated";
grant delete on table "public"."user_performance_attempt" to "service_role";
grant insert on table "public"."user_performance_attempt" to "service_role";
grant references on table "public"."user_performance_attempt" to "service_role";
grant select on table "public"."user_performance_attempt" to "service_role";
grant trigger on table "public"."user_performance_attempt" to "service_role";
grant truncate on table "public"."user_performance_attempt" to "service_role";
grant update on table "public"."user_performance_attempt" to "service_role";

-- Row Level Security Policies for user_performance_attempt
CREATE POLICY "Enable users to insert their own performance attempts" ON "public"."user_performance_attempt"
    FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable users to read their own performance attempts" ON "public"."user_performance_attempt"
    FOR SELECT USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable users to update their own performance attempts" ON "public"."user_performance_attempt"
    FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

alter table "public"."user_performance_attempt"
alter column id set generated always;