
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgsodium";
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

-- ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';
SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."motion_segmentation" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "videoId" bigint,
    "displayName" "text",
    "generationInfo" "text" NOT NULL,
    "data" "jsonb" NOT NULL,
    "createdFor" "uuid"
);

-- ALTER TABLE "public"."motion_segmentation" OWNER TO "postgres";

ALTER TABLE "public"."motion_segmentation" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."motion_segmentation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."motion_userstate" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "video_id" bigint,
    "segmentation_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "plan" "jsonb" NOT NULL
    "progress" "jsonb" NOT NULL
);

-- ALTER TABLE "public"."motion_userstate" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."motion_video" (
    "id" bigint NOT NULL,
    "displayName" "text" NOT NULL,
    "uploader" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "videoSrc" "text" NOT NULL,
    "thumbnailSrc" "text" NOT NULL,
    "height" integer NOT NULL,
    "width" integer NOT NULL,
    "videoDuration" double precision NOT NULL,
    "motionStart" double precision NOT NULL,
    "motionEnd" double precision NOT NULL,
    "fps" double precision NOT NULL,
    "detectedBpm" double precision,
    "detectedBpmOffset" double precision,
    "manualBpm" double precision
);

-- ALTER TABLE "public"."motion_video" OWNER TO "postgres";

ALTER TABLE "public"."motion_video" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."motion_video_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone,
    "username" "text",
    "full_name" "text",
    "avatar_url" "text",
    CONSTRAINT "username_length" CHECK (("char_length"("username") >= 3))
);

-- ALTER TABLE "public"."profiles" OWNER TO "postgres";

ALTER TABLE ONLY "public"."motion_segmentation"
    ADD CONSTRAINT "motion_segmentation_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."motion_userstate"
    ADD CONSTRAINT "motion_userstate_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."motion_userstate"
    ADD CONSTRAINT "motion_userstate_user_id_video_id_segmentation_id_key" UNIQUE ("user_id", "video_id", "segmentation_id");

ALTER TABLE ONLY "public"."motion_video"
    ADD CONSTRAINT "motion_video_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");

ALTER TABLE ONLY "public"."motion_segmentation"
    ADD CONSTRAINT "motion_segmentation_createdFor_fkey" FOREIGN KEY ("createdFor") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."motion_segmentation"
    ADD CONSTRAINT "motion_segmentation_video_fkey" FOREIGN KEY ("videoId") REFERENCES "public"."motion_video"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."motion_userstate"
    ADD CONSTRAINT "motion_userstate_segmentation_id_fkey" FOREIGN KEY ("segmentation_id") REFERENCES "public"."motion_segmentation"("id");

ALTER TABLE ONLY "public"."motion_userstate"
    ADD CONSTRAINT "motion_userstate_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");

ALTER TABLE ONLY "public"."motion_userstate"
    ADD CONSTRAINT "motion_userstate_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."motion_video"("id");

ALTER TABLE ONLY "public"."motion_video"
    ADD CONSTRAINT "motion_video_uploader_fkey" FOREIGN KEY ("uploader") REFERENCES "public"."profiles"("id");


ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

CREATE POLICY "Enable users to delete their own user models" ON "public"."motion_userstate" FOR DELETE USING (("auth"."uid"() = "user_id"));
CREATE POLICY "Enable users to insert their own user models" ON "public"."motion_userstate" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "Enable users to read their own user models" ON "public"."motion_userstate" FOR SELECT USING (("auth"."uid"() = "user_id"));
CREATE POLICY "Enable users to update their own user models" ON "public"."motion_userstate" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));
CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));

CREATE POLICY "Allow users to select unassigned or their own motion videos" ON "public"."motion_video"
FOR SELECT
USING (
    "uploader" IS NULL OR "uploader" = "auth"."uid"()
);

CREATE POLICY "Allow access to motion segmentations for own or unassigned" ON "public"."motion_segmentation"
FOR SELECT
USING (
    "createdFor" IS NULL OR "createdFor" = "auth"."uid"()
);

ALTER TABLE "public"."motion_segmentation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."motion_userstate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."motion_video" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";

GRANT ALL ON TABLE "public"."motion_segmentation" TO "anon";
GRANT ALL ON TABLE "public"."motion_segmentation" TO "authenticated";
GRANT ALL ON TABLE "public"."motion_segmentation" TO "service_role";

GRANT ALL ON SEQUENCE "public"."motion_segmentation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."motion_segmentation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."motion_segmentation_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."motion_userstate" TO "anon";
GRANT ALL ON TABLE "public"."motion_userstate" TO "authenticated";
GRANT ALL ON TABLE "public"."motion_userstate" TO "service_role";

GRANT ALL ON TABLE "public"."motion_video" TO "anon";
GRANT ALL ON TABLE "public"."motion_video" TO "authenticated";
GRANT ALL ON TABLE "public"."motion_video" TO "service_role";

GRANT ALL ON SEQUENCE "public"."motion_video_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."motion_video_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."motion_video_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
