# A GitHub action which will count and aggregate the contributions of each author in terms of numbers of lines
# created and deleted. This is cumulative across commits, so if an author writes 10 lines and then deletes those lines
# in a later commit, it will count as +10 -10 lines, as opposed to +0 +0
name: Count Lines of Code in Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install git
    - name: Install git
      run: sudo apt-get install -y git

    # Step 4: Fetch pull request changes
    - name: Fetch pull request changes
      run: |
        git fetch origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/head:refs/remotes/origin/pull/${{ github.event.pull_request.number }}/head

    # Step 5: Debugging - Show fetched refs
    - name: Debugging - Show fetched refs
      run: git show-ref

    - name: Test git log -p
      run: |
        git log --shortstat --pretty=format:"%an" origin/${{ github.event.pull_request.base.ref }}..origin/pull/${{ github.event.pull_request.number }}/head

    - name: Test git diff cmd
      run: | 
        git diff origin/${{ github.event.pull_request.base.ref }}..origin/pull/${{ github.event.pull_request.number }}/head

    # Step 6: Count lines of code by author and aggregate results
    #   The awk command is the star of the show here, responsible for parsing the git log output
    #   and aggregating the counts by author.
    - name: Count lines of code by author
      id: count-lines
      run: |
        git log --numstat --pretty=format:"%an" origin/${{ github.event.pull_request.base.ref }}..origin/pull/${{ github.event.pull_request.number }}/head | \
        awk '
          BEGIN { added = 0; removed = 0; author = ""; }
          /^[^ \t0-9]/ {
            if (author != "") {
              authors[author]["added"] += added;
              authors[author]["removed"] += removed;
              added = 0; removed = 0;
            }
            author = $0;
            if (!(author in authors)) {
              authors[author]["added"] = 0;
              authors[author]["removed"] = 0;
            }
            next;
          }
          /^[0-9]/ {
            added += $1;
            removed += $2;
            next;
          }
          { next; }
          END {
            if (author != "") {
              authors[author]["added"] += added;
              authors[author]["removed"] += removed;
            }
            for (author in authors) {
              print author ": +" authors[author]["added"] " -" authors[author]["removed"];
            }
          }
        ' > results.txt
        cat results.txt
      continue-on-error: true

    # Step 7: Read results from the file and set as output
    - name: Read results
      id: read-results
      run: |
        echo "results<<EOF" >> $GITHUB_OUTPUT
        cat results.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    # Step 8: Find previous "Lines of Code Contribution" comment
    - name: Find previous comment
      id: find-comment
      uses: peter-evans/find-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: github-actions[bot]
        body-includes: '## Lines of Code Contribution'

    # Step 9: Create or update the comment on the pull request with the results
    - name: Create or update PR comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        mode: replace
        body: |
          ## Lines of Code Contribution
          ```
          ${{ steps.read-results.outputs.results }}
          ```
