name: Count Lines of Code in Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install git
      run: sudo apt-get install -y git

    - name: Fetch pull request changes
      run: |
        git fetch origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/head:refs/remotes/origin/pull/${{ github.event.pull_request.number }}/head

    - name: Debugging: Show fetched refs
      run: git show-ref

    - name: Count lines of code by author
      id: count-lines
      run: |
        git log -p --pretty=format:"%an" origin/${{ github.event.pull_request.base.ref }}..origin/pull/${{ github.event.pull_request.number }}/head | \
        awk '
          BEGIN { author = ""; added = 0; removed = 0; }
          /^Author:/ { author = $2; }
          /^+/ && !/^+++/ { if ($0 !~ /^+$/) added++; }
          /^-/ && !/^---/ { if ($0 !~ /^-$/) removed++; }
          END { print author ": +" added " -" removed; }
        ' > results.txt
        cat results.txt
      continue-on-error: true

    - name: Read results
      id: read-results
      run: echo "::set-output name=results::$(cat results.txt)"

    - name: Create PR comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Lines of Code Contribution
          ```
          ${{ steps.read-results.outputs.results }}
          ```
